// Generated by CoffeeScript 1.7.1
var PI, SegmentPaths, abs, atan2, cos, defineProperty, fuzzyEqual, hypot, isNumber, max, min, roundTo, sin, sqrt, util;

sin = Math.sin, cos = Math.cos, atan2 = Math.atan2, sqrt = Math.sqrt, abs = Math.abs, max = Math.max, min = Math.min, PI = Math.PI;

util = require('./utilities');

isNumber = util.isNumber, fuzzyEqual = util.fuzzyEqual, hypot = util.hypot, roundTo = util.roundTo;

defineProperty = Object.defineProperty;

SegmentPaths = (function() {
  var defProp;

  function SegmentPaths(segmentArray) {
    if (this instanceof NumberPair) {
      Object.defineProperty(this, '_segments', {
        enumerable: false,
        value: segmentArray.slice(0)
      });
    }
  }

  SegmentPaths.prototype.copy = function() {
    return new this.constructor(this._segments);
  };

  defProp = util.defProp.bind(SegmentPaths);

  return SegmentPaths;

})();
