// Generated by CoffeeScript 1.6.2
var defineProperty, flatten, isNumber,
  __slice = [].slice;

isNumber = function() {
  var obj, objs, _i, _len;

  objs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  for (_i = 0, _len = objs.length; _i < _len; _i++) {
    obj = objs[_i];
    if (!((obj != null) && ((obj === +obj) || (toString.call(obj) === '[object Number]')))) {
      return false;
    }
  }
  return true;
};

defineProperty = Object.defineProperty;

flatten = function(array) {
  return array.reduce(function(memo, value) {
    if (Array.isArray(value)) {
      return memo.concat(flatten(value));
    }
    memo.push(value);
    return memo;
  }, []);
};

module.exports = {
  fuzzyEqual: function(me, that, precision) {
    if (precision == null) {
      precision = 0.001;
    }
    return (1.0 - Math.abs(me - that) / precision) >= 0;
  },
  hypot: function(me, y) {
    return Math.sqrt(me * me + y * y);
  },
  square: function(val) {
    return val * val;
  },
  roundTo: function(me, nearest) {
    if (nearest == null) {
      nearest = 1;
    }
    return Math.round(me / nearest) * nearest;
  },
  exclusivelyBetween: function(me, lo, hi) {
    return (lo < me && me < hi);
  },
  inclusivelyBetween: function(me, lo, hi) {
    return (lo <= me && me <= hi);
  },
  getName: function(obj) {
    var results;

    results = /function (.+?)\(/.exec(obj.toString());
    if ((results != null ? results.length : void 0) > 1) {
      return results[1];
    } else {
      return "";
    }
  },
  isNumber: isNumber,
  defProp: function(obj) {
    var key, name, names, opts, _results;

    _results = [];
    for (key in obj) {
      opts = obj[key];
      names = key.split(',');
      _results.push((function() {
        var _i, _len, _results1,
          _this = this;

        _results1 = [];
        for (_i = 0, _len = names.length; _i < _len; _i++) {
          name = names[_i];
          name = name.trim();
          defineProperty(this.prototype, name, opts);
          if (opts.set != null) {
            _results1.push((function(name) {
              return defineProperty(_this.prototype, name + "_", {
                value: function(val) {
                  this[name] = val;
                  return this;
                }
              });
            })(name));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      }).call(this));
    }
    return _results;
  },
  get: function(obj) {
    var fn, key, name, names, _results;

    _results = [];
    for (key in obj) {
      fn = obj[key];
      names = key.split(',');
      _results.push((function() {
        var _i, _len, _results1;

        _results1 = [];
        for (_i = 0, _len = names.length; _i < _len; _i++) {
          name = names[_i];
          _results1.push(defineProperty(this.prototype, name.trim(), {
            get: fn
          }));
        }
        return _results1;
      }).call(this));
    }
    return _results;
  },
  flatten: flatten,
  doPairs: function(obj, fn) {
    var i, key, n, val, _results;

    if (fn == null) {
      fn = function(a, b, i, i1, i2) {
        return [a, b];
      };
    }
    i = 0;
    _results = [];
    for (key in obj) {
      val = obj[key];
      if ((!isNaN(n = parseInt(key))) && (obj[n + 1] != null)) {
        _results.push(fn.call(obj, val, obj[1 + n], i++, n, 1 + n));
      }
    }
    return _results;
  },
  clump: function(arr, n) {
    var i, j, _i, _ref, _results;

    if (n == null) {
      n = 2;
    }
    _results = [];
    for (j = _i = 0, _ref = arr.length; n > 0 ? _i < _ref : _i > _ref; j = _i += n) {
      _results.push((function() {
        var _j, _results1;

        _results1 = [];
        for (i = _j = 0; 0 <= n ? _j < n : _j > n; i = 0 <= n ? ++_j : --_j) {
          if ((i + j) < arr.length) {
            _results1.push(arr[i + j]);
          }
        }
        return _results1;
      })());
    }
    return _results;
  }
};
